apiVersion: v1
kind: Service
metadata:
  name: spring-boot-https-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-https
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443